services:
  purr-next:
    image: purr-next-dev
    container_name: "PURRNext"
    volumes:
      - ./Content:/PURRNext/Content
      - ./Data:/PURRNext/Data
    #ports:
    #  - 5064:4096 #Live UI
    #env_file:
    #  - ./.env # Deprecated as paths are now hardcoded
    command: [
      "Docker",
      "--db=SQL"
    ]